services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - visualizer
    volumes:
      - ./work:/app/work
      - ./backend/data:/app/data
    environment:
      OPT_PATH: "opt"
      WORK_PATH: "/app/work"
      DATASOURCE_URL: "jdbc:sqlite:/app/data/visualiser.db"
      FRONT_PATH: "http://front:80"

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
      args:
        REACT_APP_BACKEND_URL: "http://localhost:8080"
        REACT_APP_CONTAINER: "true"
    ports:
      - "3000:80"
    networks:
      - visualizer

networks:
  visualizer:
    driver: bridge
